name: parkeringsapp
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ^3.5.3

dependencies:
  # Add your dependencies here.

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  parkeringsapp:
    main: main
